### PR TITLE
[BUGFIX] Fix RenderViewHelper request handling for TYPO3 v12

### LINKED ISSUE #28: Fluid ViewHelper fails in TYPO3 v12 due to invalid request access
### Describe the bug

The custom Fluid ViewHelper `FelixNagel\Pluploadfe\ViewHelpers\RenderViewHelper` fails in TYPO3 v12 because it tries to access the PSR-7 request via `$renderingContext->getAttribute(ServerRequestInterface::class)`.

In TYPO3 v12, the request is not guaranteed to be available as a RenderingContext attribute, which leads to a runtime exception during rendering.

### To Reproduce

1. Install pluploadfe in TYPO3 v12.x
2. Render Fluid template using `<plupload:render … />`
3. The ViewHelper calls `RenderingContext->getAttribute(ServerRequestInterface::class)`
4. Frontend rendering fails with an exception

### Expected behavior

The ViewHelper should retrieve the PSR-7 request in a TYPO3-12-compatible way and work reliably in frontend rendering contexts.

### Actual behavior

A runtime exception is thrown:

```
RuntimeException: An attribute of type Psr\Http\Message\ServerRequestInterface has not been set
```

### TYPO3 Version

TYPO3 12.x

### Extension Version

pluploadfe 8.2

### Affected code

`Classes/ViewHelpers/RenderViewHelper.php`

### Additional context

In TYPO3 v12, the PSR-7 request must be accessed via `RenderingContext->getRequest()`.

### PR DESCRIPTION
**Pull request by ErHaWeb**
Adjust RenderViewHelper to retrieve the PSR-7 request in a TYPO3 v12–compatible way by using RenderingContext->getRequest(), while keeping the attribute-based access for TYPO3 v13+.

Resolves #28

### CODE REVIEW

File: Classes/Controller/Pi1Controller.php [hunk 1]
```diff
@@ -215,6 +207,12 @@ protected function getPageRenderer(): PageRenderer
     protected function getFeEnableFields(string $table): string
     {
         $pageRepository = GeneralUtility::makeInstance(PageRepository::class);
+
+        // @todo Remove this when TYPO3 12 is no longer relevant!
```
Comment (fnagel) [inline Classes/Controller/Pi1Controller.php]: This has been reported and already been fixed in the 8.x branch. See https://github.com/fnagel/pluploadfe/commit/a35634740f5d9292d64d7d937ac6d5280a020cd7

It looks like we were working on the bug fix at the same time 🙈

**Review by fnagel — CHANGES_REQUESTED** [review]

File: Classes/Controller/Pi1Controller.php (hunk 1 above)
Comment (ErHaWeb) [reply Classes/Controller/Pi1Controller.php]: Oops, I didn't think you'd be so quick. Well, better two solutions than none at all 😉

**Comment by ErHaWeb** [comment]
I have now adjusted the pull request. It now only resolves #28.

File: Classes/Controller/Pi1Controller.php (hunk 1 above)
Comment (ErHaWeb) [reply Classes/Controller/Pi1Controller.php]: I have now limited this PR to #28 so that it can be merged directly.

**Review by fnagel — APPROVED** [review]
